name: harmony
description: "An app that gives the user information on lyrics, albums, artists, and more!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audio_video_progress_bar: ^2.0.3
  auto_size_text: ^3.0.0
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_appauth: ^6.0.6
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^4.2.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.2
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shimmer_animation: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0
  freezed: ^2.5.2
          
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - .env