name: harmony
description: "An app that gives the user information on lyrics, albums, artists, and more!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audio_video_progress_bar: ^2.0.3
  flutter:
    sdk: flutter
  flutter_gradient_animation_text: ^1.0.2
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  flutter_web_auth_2: ^3.1.2
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  introduction_screen: ^3.1.14
  riverpod_annotation: ^2.3.5
  spotify_api: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/