name: Build Android
on: [push, pull_request, workflow_dispatch]

permissions: read-all

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Secrets Environment File
        run: |
          echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" >> .env
          echo "SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> .env

      - name: Setup Java Environment        
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Build App Bundle
        run: flutter build appbundle